// import './jsxstudy.js'
// import './first-component.js'
// import './animal-container.js'
// import './props-basic.js'
// import './sol_greeting.js'
// import './person-profile.js'
// import './props-children.js'
// import './sol_slot_machine.js'
// import './sol_slot_machine_T.js'
import './state-study-1.js'